### ISSUE TITLE
      Tipografía 

### ISSUE THREAD

**Issue by MacRoberto** [MacRoberto/travel-segundo-parcial#13]
- [x] Agregar tipografía Open Sans

**Comment by LuisAmir04** [comment]
Se realizo y cerro el pull request de Tipografía

**Comment by MacRoberto** [comment]
Abrí este issue nuevamente, porque no veo evidencia de su realización.

**Comment by LuisAmir04** [comment]
fixes: https://github.com/MacRoberto/travel-segundo-parcial/pull/18

- [x] Se cumplió con agregar tipografía tipo Open Sans a la web

![Screenshot_68](https://github.com/user-attachments/assets/94754203-5991-49eb-b6fb-5613dcf41d6f)

**Comment by MacRoberto** [comment]
Se cerró correctamente
