### ISSUE TITLE
Git Hub Page

### ISSUE THREAD

**Issue by MacRoberto** [MacRoberto/travel-segundo-parcial#15]
Agregar proyecto a GitHub page:

- [x] Hacer investigación referente a este proceso.
- [x] Explicarle este proceso al equipo de desarrolladores.
- [x] Subir el proyecto a GitHub page.

**Comment by JJS74** [comment]
Proyecto subido a github pages completo con apoyo del líder de proyecto @MacRoberto .
Las fuentes de investigación para poder realizar esta actividad son las siguientes:
fixes:https://youtu.be/8IdBAysf-U4?si=reYK8r6Hu0RxXuQe, https://youtu.be/sLTNgxxSBR4?si=bKesQ3RWeSXvRXN8, https://youtu.be/wyRfN5oLzx4?si=WZghxV4l8mG66vTf, https://youtu.be/QyFcl_Fba-k?si=HXA2ClBz1j0ey4Pq
La URL de nuestro git hub page es la siguiente:
https://github.com/MacRoberto/travel-segundo-parcial.io
