### ISSUE TITLE
Maquetado de Hero

### ISSUE THREAD

**Issue by MacRoberto** [MacRoberto/travel-segundo-parcial#2]
Para esta actividad se requiere:

- [x] Codificar en archivos HTML y CSS los códigos necesarios para su desarrollo.
- [x] Agregar archivos necesarios para este desarrollo (imagen, logo, ...).
- [x] Crear una rama (branch)con nombre "Hero" para subir el trabajo.
- [x] Hacer commit y pull request hacia el main.

**Comment by Fernando7Josue** [comment]
fixes: https://github.com/MacRoberto/travel-segundo-parcial/pull/16

Se realizo el hero.

1. Se codifico el html y css
2. Se agrego las imagenes correspondientes del hero
3. Se creo una rama con el titulo correspondiente
4. Se hizo el commit y el pull request

**Comment by Fernando7Josue** [comment]
fixes:https://github.com/MacRoberto/travel-segundo-parcial/pull/16

Ya se termino este issue, solo falta el header.
