### ISSUE TITLE
Action

### ISSUE THREAD

**Issue by MacRoberto** [MacRoberto/travel-segundo-parcial#20]
Debido a un descuido humano, se borró algunos códigos correspondientes al .action, este issue es para restablecer esos cambios inesperados que se produjeron. 

- [x] Crear una rama para subir estas correcciones.
- [x] Hacer commit y Pull Request al main de las correcciones tomadas.
- [x] Favor de anexar los cambios que se hicieron.

**Comment by Fernando7Josue** [comment]
fixes: https://github.com/MacRoberto/travel-segundo-parcial/pull/21

Se corrigío el error de header.

**Comment by Fernando7Josue** [comment]
fixes: https://github.com/MacRoberto/travel-segundo-parcial/pull/21

**Comment by Fernando7Josue** [comment]
Tambien se corrigío la topografía ya que ocurrío un error en el css.

![image](https://github.com/user-attachments/assets/f7c4ad8c-cdda-4e41-a450-60fef63af3d8)
