### ISSUE TITLE
Best packege

### ISSUE THREAD

**Issue by MacRoberto** [MacRoberto/travel-segundo-parcial#27]
Como integrante del equipo de desarrollo de Travel Goo, se hace este issue con la finalidad de solicitar ayuda para entender lo que esta sucediendo con el maquetado de Best package; ya que, se muestra desordenado y superpuesto los objetos en Chrome y edge. Al ejecutar el código con Live service todo parece estar bien..
![image](https://github.com/user-attachments/assets/35b5a1c7-439c-402f-9f82-6a58505ff419)
![image](https://github.com/user-attachments/assets/416934c9-6320-41c3-9618-a1c913822344)

**Comment by Fernando7Josue** [comment]
Lamentablemente no se pudo hacer que las imagenes se pudiesen ver.
pero si se acomodo en run and bug

**Comment by Fernando7Josue** [comment]
![image](https://github.com/user-attachments/assets/ea2052a7-a50f-489e-a266-ff37f8189637)
