### ISSUE TITLE
corrección Best package 

### ISSUE THREAD

**Issue by MacRoberto** [MacRoberto/travel-segundo-parcial#28]
Debido a que se encontraron dificultades en la ejecución correcta de Best package en chrome se disponen a realizar los siguientes cambios:

- [x] Ordenar la estructura de los códigos correspondientes.
- [x] Eliminar códigos vacíos que no cumplen ninguna función.
- [x] Hacer el "commit desde la rama de best package de las correciones.
- [x] Hacer pull request al main de las correcciones.

**Comment by Fernando7Josue** [comment]
Se realizo lo pendiente de este issue.
