### ISSUE TITLE
Maquetado de Header

### ISSUE THREAD

**Issue by MacRoberto** [MacRoberto/travel-segundo-parcial#4]
- [x] Realizar códigos para el archivo HTML y CSS correspondientes al header.
- [x] Agregar archivos necesarios para este desarrollo (imagen, logo, ...)
- [x] Crear un Branch con nombre "Header" para subir el avance.
- [x] Hacer un commit y pull request hacia el main de este trabajo.

**Comment by MacRoberto** [comment]
Se cambió la asignación de este Issues a Fernando Josué debido a que Emiliano no se presentó a las primeras clases de este parcial que son importantes para realizar esta actividad.

**Comment by Fernando7Josue** [comment]
fixes: https://github.com/MacRoberto/travel-segundo-parcial/pull/17

Se realizo el hero

1. Se agrego lo que faltaba del primer issue que era el hero
2. Se agrego las logos de la parte de header
3. Se realizo la branch llamada Header
4. Se hizo el pull request y el commit

**Comment by Fernando7Josue** [comment]
fixes: https://github.com/MacRoberto/travel-segundo-parcial/pull/17

Se reviso y se cerro el pull request de header
