### ISSUE TITLE
Maquetado Our services 

### ISSUE THREAD

**Issue by MacRoberto** [MacRoberto/travel-segundo-parcial#5]
- [x] Realizar códigos en HTML Y CSS correspondiente a esta actividad.
- [x] Agregar archivos necesarios para completar esta tarea.
- [x] Crear un branch para subir esta actividad.
- [x] Hacer commit y pull request hacia el main de este trabajo.

**Comment by JJS74** [comment]
fixes #https://github.com/MacRoberto/travel-segundo-parcial/issues/5

- [x]  Realizar códigos en HTML Y CSS correspondiente a esta actividad.
- [x]  Crear un branch para subir esta actividad.
- [x]  Se añadió un efecto de viñeta a para el hero principal
- [x]  Se esta trabajando en el issue Our Service

**Comment by JJS74** [comment]
fixes #https://github.com/MacRoberto/travel-segundo-parcial/issues/5

![image](https://github.com/user-attachments/assets/fb64ddd3-7039-4467-ac8a-869c742eee8c)

- [x] Se realizaron por completo el HTML y el CSS correspondientes a la actividad
- [x] Se creo una branch para poder subir la actividad
- [x] Se agregaron los archivos necesarios para completar la actividad
- [x] Se hizo commit y pull request
- [x] Adición de efectos visuales mínimos al proyecto

**Comment by JJS74** [comment]
fixes #https://github.com/MacRoberto/travel-segundo-parcial/issues/5

- [x] Problemas visuales referentes a los bloques de texto Our service han sido arreglados

![image](https://github.com/user-attachments/assets/d5da965d-c945-40aa-bf1e-3c35a765c4f1)

**Comment by JJS74** [comment]
fixes #5

![image](https://github.com/user-attachments/assets/20b93d9b-7747-45bd-8fc7-d232f231701b)

- [x] Optimizacion minima de codigo
- [x] Se añadio una nueva imagen a ticket booking que soluciona algunos problemas minimos

**Comment by MacRoberto** [comment]
Excelente trabajo. Todo perfecto.
