### ISSUE TITLE
Maquetado Best Services 

### ISSUE THREAD

**Issue by MacRoberto** [MacRoberto/travel-segundo-parcial#6]
Pendiente...

**Comment by LuisAmir04** [comment]
Se reabrio el issue para poder añadir el pull request cerrado, se cumplio con el maquetado requerido.
https://github.com/MacRoberto/travel-segundo-parcial/pull/24
![Screenshot_10](https://github.com/user-attachments/assets/b503bcb7-bd40-4bbb-b1c8-e2342ddb4b04)
