### ISSUE TITLE
Maquetado Best Package

### ISSUE THREAD

**Issue by MacRoberto** [MacRoberto/travel-segundo-parcial#8]
Se debe maquetar la sesión de Best Package, donde se realizará los siguientes puntos:

- [x] Realizar códigos HTML Y CCS
- [x] Crear botones de paquetes de viaje a distintas partes del mundo, 5 de los principales lugares y uno asignado para otros 
       lugares.
- [x] 3 Card de visualización previa a tres lugares atractivos con información del paquete , precio, días , el lugar y descripción.
- [x] Crear branch para subir el trabajo.
- [x] Hacer commit y pull request al main.
- [x] Otras actividades no mencionados.

**Comment by Fernando7Josue** [comment]
fixes: https://github.com/MacRoberto/travel-segundo-parcial/pull/26

1. Se realizo los codigos correspondientes para el trabajo.
2. Se agregaron las imágenes correspondientes al trabajo.
3. Se creo la branch.

![2024-11-08](https://github.com/user-attachments/assets/692e11d7-6667-4a6b-9545-9956eb592e13)

**Comment by Fernando7Josue** [comment]
fixes: https://github.com/MacRoberto/travel-segundo-parcial/pull/26

1.Se realizo los codigos correspondientes para el trabajo.
2.Se agregaron las imágenes correspondientes al trabajo.
3.Se creo la branch.


![2024-11-08](https://github.com/user-attachments/assets/6bebaed6-8ffd-4eeb-b895-fe012de3a11f)

**Comment by MacRoberto** [comment]
Excelente trabajo
